-- 태그 데이터

-- 태그
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (1, '엔터테인먼트', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/entertainment_icon.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/entertainment_icon_selected.svg', 'null', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (2, '주차/출차', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_parking_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_parking_blue.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/bg/parking.png', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (3, '추위/더위', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_temperature_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_temperature_blue.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/bg/temperature.png', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (4, '퍼포먼스', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_performance_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_performance_blue.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/bg/performance.png', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (5, '주행안전', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_safety_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_safety_blue.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/bg/safety.png', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (6, '스타일', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_style_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_style_blue.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/bg/style.png', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (7, '사용편의', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_convenience_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_convenience_blue.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/bg/convenience.png', 0);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (8, '전체', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_all_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_all_blue.svg', 'null', 5);
INSERT INTO ca_art.tag (tag_id, name, icon, icon_selected, image, priority) VALUES (9, '대표', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_main_black.svg', 'https://caart-app-s3-bucket.s3.ap-northeast-2.amazonaws.com/image/tag/icon/category_icon_main_blue.svg', 'null', 4);
